<?php
/**
 * Setting Lexicon Entries for PDFResource
 *
 * @package pdfresource
 * @subpackage lexicon
 */
$_lang['area_pdf'] = '';
$_lang['area_resource'] = '';
$_lang['area_template'] = '';
$_lang['setting_pdfresource.author'] = '';
$_lang['setting_pdfresource.author_desc'] = '';
$_lang['setting_pdfresource.creator'] = '';
$_lang['setting_pdfresource.creator_desc'] = '';
$_lang['setting_pdfresource.cssTpl'] = '';
$_lang['setting_pdfresource.cssTpl_desc'] = '';
$_lang['setting_pdfresource.customFonts'] = '';
$_lang['setting_pdfresource.customFonts_desc'] = '';
$_lang['setting_pdfresource.customFontsFolder'] = '';
$_lang['setting_pdfresource.customFontsFolder_desc'] = '';
$_lang['setting_pdfresource.debug'] = '';
$_lang['setting_pdfresource.debug_desc'] = '';
$_lang['setting_pdfresource.defaultFont'] = '';
$_lang['setting_pdfresource.defaultFont_desc'] = '';
$_lang['setting_pdfresource.defaultFontSize'] = '';
$_lang['setting_pdfresource.defaultFontSize_desc'] = '';
$_lang['setting_pdfresource.format'] = '';
$_lang['setting_pdfresource.format_desc'] = '';
$_lang['setting_pdfresource.generateOnPrerender'] = '';
$_lang['setting_pdfresource.generateOnPrerender_desc'] = '';
$_lang['setting_pdfresource.mgb'] = '';
$_lang['setting_pdfresource.mgb_desc'] = '';
$_lang['setting_pdfresource.mgf'] = '';
$_lang['setting_pdfresource.mgf_desc'] = '';
$_lang['setting_pdfresource.mgh'] = '';
$_lang['setting_pdfresource.mgh_desc'] = '';
$_lang['setting_pdfresource.mgl'] = '';
$_lang['setting_pdfresource.mgl_desc'] = '';
$_lang['setting_pdfresource.mgr'] = '';
$_lang['setting_pdfresource.mgr_desc'] = '';
$_lang['setting_pdfresource.mgt'] = '';
$_lang['setting_pdfresource.mgt_desc'] = '';
$_lang['setting_pdfresource.mode'] = '';
$_lang['setting_pdfresource.mode_desc'] = '';
$_lang['setting_pdfresource.mPDFMethods'] = '';
$_lang['setting_pdfresource.mPDFMethods_desc'] = '';
$_lang['setting_pdfresource.orientation'] = '';
$_lang['setting_pdfresource.orientation_desc'] = '';
$_lang['setting_pdfresource.ownerPassword'] = '';
$_lang['setting_pdfresource.ownerPassword_desc'] = '';
$_lang['setting_pdfresource.pdfTpl'] = '';
$_lang['setting_pdfresource.pdfTpl_desc'] = '';
$_lang['setting_pdfresource.pdfTv'] = '';
$_lang['setting_pdfresource.pdfTv_desc'] = '';
$_lang['setting_pdfresource.pdfTvLive'] = '';
$_lang['setting_pdfresource.pdfTvLive_desc'] = '';
$_lang['setting_pdfresource.pdfTvOptions'] = '';
$_lang['setting_pdfresource.pdfTvOptions_desc'] = '';
$_lang['setting_pdfresource.permissions'] = '';
$_lang['setting_pdfresource.permissions_desc'] = '';
$_lang['setting_pdfresource.processTVs'] = '';
$_lang['setting_pdfresource.processTVs_desc'] = '';
$_lang['setting_pdfresource.tvPrefix'] = '';
$_lang['setting_pdfresource.tvPrefix_desc'] = '';
$_lang['setting_pdfresource.userPassword'] = '';
$_lang['setting_pdfresource.userPassword_desc'] = '';
